### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by phillbooth** [PHOENIX-MEDIA/Magento-WorldPay#18]
I have made sure permissions and cache have bee done but I cannot get the plugin to install, tried via FTP and Magento Downloader.

`a:5:{i:0;s:66:"Invalid config field backend model: worldpay/config_backend_instid";i:1;s:1715:"#0 /home/alternat/public_html/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(328): Mage::throwException('Invalid config ...')
#1 /home/alternat/public_html/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(229): Mage_Adminhtml_Block_System_Config_Form->initFields(Object(Varien_Data_Form_Element_Fieldset), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#2 /home/alternat/public_html/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(164): Mage_Adminhtml_Block_System_Config_Form->_initGroup(Object(Varien_Data_Form), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#3 /home/alternat/public_html/app/code/core/Mage/Adminhtml/Block/System/Config/Edit.php(92): Mage_Adminhtml_Block_System_Config_Form->initForm()
#4 /home/alternat/public_html/app/code/core/Mage/Adminhtml/controllers/System/ConfigController.php(107): Mage_Adminhtml_Block_System_Config_Edit->initForm()
#5 /home/alternat/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_System_ConfigController->editAction()
#6 /home/alternat/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('edit')
#7 /home/alternat/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#8 /home/alternat/public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#9 /home/alternat/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#10 /home/alternat/public_html/index.php(85): Mage::run('', 'store')
#11 {main}";s:3:"url";s:93:"/index.php/runtimeuk/system_config/edit/section/payment/key/45334ba48b877d19be10a1e11330e95e/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}`

**Comment by underthecocotree** [comment]
Try to set the Current Configuration Scope to the shop view (Probably the Default store view) That stops the error from appearing for me.
